#!/bin/sh
set -e

NETWORK="${FRIGATE_NETWORK:-mainnet}"
HOME_DIR="/data/frigate"
NET_DIR="${HOME_DIR}/${NETWORK}"
CONFIG_FILE="${NET_DIR}/config.toml"

mkdir -p "${NET_DIR}"

DEFAULT_START_HEIGHT=0
case "${NETWORK}" in
    mainnet) DEFAULT_START_HEIGHT=709632 ;;
    *) DEFAULT_START_HEIGHT=0 ;;
esac
START_HEIGHT="${FRIGATE_START_HEIGHT:-${DEFAULT_START_HEIGHT}}"

if [ -z "${APP_BITCOIN_NODE_IP}" ] || [ -z "${APP_BITCOIN_RPC_PORT}" ]; then
    echo "ERROR: APP_BITCOIN_NODE_IP and APP_BITCOIN_RPC_PORT must be set"
    exit 1
fi

if [ -z "${APP_BITCOIN_RPC_USER}" ] || [ -z "${APP_BITCOIN_RPC_PASS}" ]; then
    echo "ERROR: APP_BITCOIN_RPC_USER and APP_BITCOIN_RPC_PASS must be set"
    exit 1
fi

cat > "${CONFIG_FILE}" <<EOF
# Generated by frigate-umbrel entrypoint at $(date -Iseconds)
[core]
connect = true
server = "http://${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}"
authType = "USERPASS"
auth = "${APP_BITCOIN_RPC_USER}:${APP_BITCOIN_RPC_PASS}"

[index]
startHeight = ${START_HEIGHT}

[scan]
computeBackend = "${FRIGATE_COMPUTE_BACKEND:-CPU}"

[server]
port = ${FRIGATE_PORT:-57001}
EOF

echo "Frigate starting on network=${NETWORK} startHeight=${START_HEIGHT} bitcoind=${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}"

exec /opt/frigate/bin/frigate -n "${NETWORK}" -d "${HOME_DIR}"
