#!/bin/bash
set -e

NETWORK="${FRIGATE_NETWORK:-mainnet}"
HOME_DIR="/data/frigate"
NET_DIR="${HOME_DIR}/${NETWORK}"
CONFIG_FILE="${NET_DIR}/config.toml"
BITCOIN_DATA_DIR="${FRIGATE_BITCOIN_DATA_DIR:-/data/.bitcoin}"
LOG_FILE="/data/frigate.log"

mkdir -p "${NET_DIR}"

# Truncate log on start so the dashboard tail is bounded after restarts.
: > "${LOG_FILE}"
chmod 644 "${LOG_FILE}" 2>/dev/null || true

DEFAULT_START_HEIGHT=0
case "${NETWORK}" in
    mainnet) DEFAULT_START_HEIGHT=709632 ;;
    *) DEFAULT_START_HEIGHT=0 ;;
esac
START_HEIGHT="${FRIGATE_START_HEIGHT:-${DEFAULT_START_HEIGHT}}"

if [ -z "${APP_BITCOIN_NODE_IP}" ] || [ -z "${APP_BITCOIN_RPC_PORT}" ]; then
    echo "ERROR: APP_BITCOIN_NODE_IP and APP_BITCOIN_RPC_PORT must be set"
    exit 1
fi

# Pick auth method: prefer COOKIE if bitcoind data dir is mounted, fallback to USERPASS
AUTH_BLOCK=""
if [ -d "${BITCOIN_DATA_DIR}" ]; then
    COOKIE_FILE=$(find "${BITCOIN_DATA_DIR}" -maxdepth 2 -name '.cookie' -type f 2>/dev/null | head -1)
    if [ -n "${COOKIE_FILE}" ]; then
        echo "Cookie auth: found ${COOKIE_FILE}, using dataDir=${BITCOIN_DATA_DIR}"
        AUTH_BLOCK="authType = \"COOKIE\"
dataDir = \"${BITCOIN_DATA_DIR}\""
    fi
fi

if [ -z "${AUTH_BLOCK}" ]; then
    if [ -z "${APP_BITCOIN_RPC_USER}" ] || [ -z "${APP_BITCOIN_RPC_PASS}" ]; then
        echo "ERROR: no .cookie found at ${BITCOIN_DATA_DIR} and APP_BITCOIN_RPC_USER/PASS not set"
        exit 1
    fi
    echo "Userpass auth: APP_BITCOIN_RPC_USER=${APP_BITCOIN_RPC_USER}"
    AUTH_BLOCK="authType = \"USERPASS\"
auth = \"${APP_BITCOIN_RPC_USER}:${APP_BITCOIN_RPC_PASS}\""
fi

cat > "${CONFIG_FILE}" <<EOF
# Generated by frigate-umbrel entrypoint at $(date -Iseconds)
[core]
connect = true
server = "http://${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}"
${AUTH_BLOCK}

[index]
startHeight = ${START_HEIGHT}

[scan]
computeBackend = "${FRIGATE_COMPUTE_BACKEND:-CPU}"

[server]
port = ${FRIGATE_PORT:-57001}
EOF

if [ -n "${FRIGATE_BACKEND_ELECTRUM}" ]; then
    echo "backendElectrumServer = \"${FRIGATE_BACKEND_ELECTRUM}\"" >> "${CONFIG_FILE}"
    echo "Backend Electrum server: ${FRIGATE_BACKEND_ELECTRUM}"
fi

echo "Frigate starting on network=${NETWORK} startHeight=${START_HEIGHT} bitcoind=${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}"
echo "Logging to ${LOG_FILE}"

# Background poller: writes "block height N" lines to LOG_FILE every 30s so the
# dashboard regex /block height (\d+)/gi keeps matching when Frigate is idle at
# the tip (Frigate 1.5.2 only logs "Block index is up to date" in steady state).
(
    sleep 5
    while true; do
        cookie_file=$(find "${BITCOIN_DATA_DIR}" -maxdepth 2 -name '.cookie' -type f 2>/dev/null | head -1)
        if [ -n "$cookie_file" ]; then
            auth=$(cat "$cookie_file")
            response=$(curl -s --max-time 5 --user "$auth" \
                --data-binary '{"jsonrpc":"1.0","id":"f","method":"getblockcount","params":[]}' \
                -H 'content-type: application/json' \
                "http://${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}/" 2>/dev/null)
            height=$(echo "$response" | grep -oE '"result":[0-9]+' | grep -oE '[0-9]+$')
            if [ -n "$height" ]; then
                ts=$(date '+%Y-%m-%d %H:%M:%S,000')
                echo "${ts} INFO Bitcoind block height ${height}" >> "${LOG_FILE}"
            fi
        fi
        sleep 30
    done
) &

# Stream stdout+stderr to LOG_FILE via tee (bash process substitution).
# exec keeps Frigate as PID 1 so SIGTERM from Umbrel is delivered directly.
exec /opt/frigate/bin/frigate -n "${NETWORK}" -d "${HOME_DIR}" > >(tee -a "${LOG_FILE}") 2>&1
