version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: 4rkad-frigate_web_1
      APP_PORT: 8080

  web:
    image: nginx:1.27-alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/web/index.html:/tmp/index.template.html:ro
      - ${APP_DATA_DIR}/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${APP_DATA_DIR}/icon.png:/usr/share/nginx/html/icon.png:ro
      - ${APP_DATA_DIR}/web/umbrel-qr-icon.svg:/usr/share/nginx/html/umbrel-qr-icon.svg:ro
    environment:
      FRIGATE_TOR_ADDRESS: "${APP_FRIGATE_RPC_HIDDEN_SERVICE}"
      FRIGATE_VERSION: "${APP_VERSION}"
    command: ["sh", "-c", "envsubst '$$FRIGATE_TOR_ADDRESS $$FRIGATE_VERSION' < /tmp/index.template.html > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'"]

  server:
    image: ghcr.io/4rkad/frigate-umbrel:1.4.1-1@sha256:de5ba75957c3563e728322e5e3adecb64a4c94348decac59bdb85266ff038d6c
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "57001:57001"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_BITCOIN_DATA_DIR}/data:/data/.bitcoin:ro
    environment:
      APP_BITCOIN_NODE_IP: ${APP_BITCOIN_NODE_IP}
      APP_BITCOIN_RPC_PORT: ${APP_BITCOIN_RPC_PORT}
      FRIGATE_BITCOIN_DATA_DIR: "/data/.bitcoin"
      FRIGATE_BACKEND_ELECTRUM: "tcp://${APP_ELECTRS_NODE_IP}:${APP_ELECTRS_NODE_PORT}"
      FRIGATE_NETWORK: ${APP_BITCOIN_NETWORK:-mainnet}
      FRIGATE_COMPUTE_BACKEND: "CPU"
      FRIGATE_PORT: "57001"

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
    entrypoint: ["/bin/sh", "-c"]
    command: ["mkdir -p /data/app-4rkad-frigate/main && chmod 700 /data/app-4rkad-frigate/main && printf 'HiddenServiceDir /data/app-4rkad-frigate/main\\nHiddenServicePort 57001 server:57001\\n' > /tmp/torrc && exec tor -f /tmp/torrc"]
